format_version: 2
pipelines:
  TerraformProduction:
    group: TerraformPipeline
    label_template: "${TerraformStagingDeployed}.${COUNT}"
    materials:
      backend:
        git: http://git-repo:3000/gogs/terraform-pipeline-config.git
        branch: master
      TerraformStagingDeployed:
        pipeline: TerraformStaging
        stage: DeployToStaging
    stages:
      - DeployToProduction:
          jobs:
            Deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - -c
                    - ARTIFACT_FOLDER=$(echo $GO_DEPENDENCY_LABEL_TERRAFORMSTAGINGDEPLOYED | cut -d '.' -f1-2) && scripts/sync-from-s3.sh ${ARTIFACT_FOLDER} production
                - exec:
                    run_if: passed
                    working_directory: production
                    command: /bin/sh
                    arguments:
                    - -c
                    - ls -la
                - exec:
                    run_if: passed
                    working_directory: production
                    command: /bin/sh
                    arguments:
                    - -c
                    - terraform init -backend-config="backend.tfvars"
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - -c
                    - scripts/apply.sh ${GO_DEPENDENCY_LABEL_TERRAFORMSTAGINGDEPLOYED} production
                - exec:
                    run_if: passed
                    command: scripts/smoke-test.sh
                    arguments:
                    - production
