format_version: 2
pipelines:
  TerraformStaging:
    group: TerraformPipeline
    label_template: "${TerraformModuleSyncedToS3}.${COUNT}"
    materials:
      backend:
        git: http://git-repo:3000/gogs/terraform-pipeline-config.git
        branch: master
      TerraformModuleSyncedToS3:
        pipeline: TerraformCommit
        stage: SyncToS3
    stages:
      - DeployToStaging:
          jobs:
            Deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - -c
                    - scripts/sync-from-s3.sh ${GO_DEPENDENCY_LABEL_TERRAFORMMODULESYNCEDTOS3} staging
                - exec:
                    run_if: passed
                    working_directory: staging
                    command: /bin/sh
                    arguments:
                    - -c
                    - ls -la
                - exec:
                    run_if: passed
                    working_directory: staging
                    command: /bin/sh
                    arguments:
                    - -c
                    - terraform init -backend-config="backend.tfvars"
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - -c
                    - scripts/apply.sh ${GO_DEPENDENCY_LABEL_TERRAFORMMODULESYNCEDTOS3} staging
                - exec:
                    run_if: passed
                    command: scripts/smoke-test.sh
                    arguments:
                    - staging
